'use strict';
const $=id=>document.getElementById(id), enc=new TextEncoder(),dec=new TextDecoder();let db,records=[],goals=[],key,sessionPassword,lastActivity=Date.now();const money=(n,c='USD')=>(c==='ZiG'?'ZiG ':'$')+(n/100).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});const currency=r=>r.currency==='ZiG'?'ZiG':'USD';const cents=v=>Math.round(Number(v)*100);const uid=()=>crypto.randomUUID();const b64=a=>btoa(String.fromCharCode(...new Uint8Array(a)));const unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function derive(password,salt){let base=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function seal(obj,k){let iv=crypto.getRandomValues(new Uint8Array(12)),data=await crypto.subtle.encrypt({name:'AES-GCM',iv},k,enc.encode(JSON.stringify(obj)));return {iv:b64(iv),data:b64(data)}}async function unseal(blob,k){return JSON.parse(dec.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(blob.iv)},k,unb64(blob.data))))}
function openDB(){return new Promise((resolve,reject)=>{let r=indexedDB.open('ledger4',1);r.onupgradeneeded=()=>{let d=r.result;d.createObjectStore('store')};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}async function readyDB(){if(!db)db=await openDB();return db}async function get(k){const database=await readyDB();return new Promise((resolve,reject)=>{let r=database.transaction('store').objectStore('store').get(k);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}async function put(k,v){const database=await readyDB();return new Promise((resolve,reject)=>{let r=database.transaction('store','readwrite').objectStore('store').put(v,k);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)})}
async function persist(){await put('vault',await seal({records,goals},key))}function lock(){key=null;sessionPassword=null;records=[];goals=[];$('app').classList.add('hidden');$('auth').classList.remove('hidden');$('password').value='';$('authTitle').textContent='Unlock Ledger';$('authMsg').textContent=''}
async function unlock(){let p=$('password').value;if(p.length<8)throw Error('Password must have at least 8 characters');let config=await get('config');if(!config){let salt=crypto.getRandomValues(new Uint8Array(16));key=await derive(p,salt);await put('vault',await seal({records:[],goals:[]},key));await put('config',{salt:b64(salt)});}else{key=await derive(p,unb64(config.salt));let v=await unseal(await get('vault'),key);records=v.records;goals=v.goals}sessionPassword=p;$('auth').classList.add('hidden');$('app').classList.remove('hidden');$('password').value='';lastActivity=Date.now();render()}
$('authBtn').onclick=async()=>{try{await unlock()}catch(e){key=null;$('authMsg').textContent='Could not unlock: '+e.message}};
const today=()=>new Date().toLocaleDateString('en-CA');$('date').value=today();$('reportDate').value=today();function choices(){if(['saving','withdrawal'].includes($('kind').value)){$('currency').value='USD';$('currency').disabled=true}else $('currency').disabled=false;$('amountCurrency').textContent=$('currency').value;let opts='<option value="general">General savings</option>'+goals.map(g=>`<option value="${esc(g.id)}">${esc(g.name)}</option>`).join('');$('saveGoal').innerHTML=opts;$('category').innerHTML=$('kind').value==='income'?'<option>Salary</option><option>Business</option><option>Gift</option><option>Other income</option>':$('kind').value==='expense'?'<option>Groceries</option><option>Transport</option><option>Food</option><option>Utilities</option><option>Health</option><option>Entertainment</option><option>Other</option>':opts;$('savePrompt').classList.toggle('hidden',$('kind').value!=='income'||$('currency').value!=='USD')}$('kind').onchange=choices;$('currency').onchange=()=>{$('amountCurrency').textContent=$('currency').value;choices()};
function balance(c){return records.filter(r=>currency(r)===c).reduce((a,r)=>a+(r.kind==='income'?r.amount:r.kind==='expense'?-r.amount:r.kind==='saving'?-r.amount:r.kind==='withdrawal'?r.amount:0),0)}function saved(c){return records.filter(r=>currency(r)===c).reduce((a,r)=>a+(r.kind==='saving'?r.amount:r.kind==='withdrawal'?-r.amount:0),0)}
function render(){choices();$('totals').innerHTML=['USD','ZiG'].map(c=>{let rs=records.filter(r=>currency(r)===c),sum=k=>rs.filter(r=>r.kind===k).reduce((a,r)=>a+r.amount,0);return `<div class="item"><h3>${c}</h3><p>Available: <b>${money(balance(c),c)}</b></p><p>Income: ${money(sum('income'),c)} · Expenses: ${money(sum('expense'),c)}</p><p>Savings: <b>${money(saved(c),c)}</b></p></div>`}).join('');$('goals').innerHTML=goals.map(g=>{let total=records.filter(r=>r.goal===g.id&&currency(r)==='USD').reduce((a,r)=>a+(r.kind==='saving'?r.amount:r.kind==='withdrawal'?-r.amount:0),0);return `<div class="item">${esc(g.name)}: ${money(total)} / ${money(g.target)} (${Math.round(100*total/g.target)}%)</div>`}).join('');$('history').innerHTML=records.slice().reverse().map(r=>`<div class="item"><b>${esc(r.kind)} · ${money(r.amount,currency(r))}</b><br>${esc(r.date)} · ${esc(r.description||r.category||'')} ${r.image?`<br><button data-image="${esc(r.id)}">View attachment</button>`:''}</div>`).join('');$('history').querySelectorAll('[data-image]').forEach(b=>b.onclick=()=>{let r=records.find(x=>x.id===b.dataset.image);let w=window.open('','_blank');if(w){w.document.write('<title>Ledger attachment</title><img style="max-width:100%" src="'+r.image+'">');w.document.close()}});report()}
function report(){let d=new Date(($('reportDate').value||today())+'T12:00:00'),start=new Date(d),end=new Date(d),period=$('period').value;if(period==='week'){start.setDate(d.getDate()-(d.getDay()+6)%7);end=new Date(start);end.setDate(start.getDate()+6)}else if(period==='month'){start.setDate(1);end=new Date(d.getFullYear(),d.getMonth()+1,0)}else{start=new Date(d.getFullYear(),0,1);end=new Date(d.getFullYear(),11,31)}let iso=x=>x.getFullYear()+'-'+String(x.getMonth()+1).padStart(2,'0')+'-'+String(x.getDate()).padStart(2,'0');let rs=records.filter(r=>r.date>=iso(start)&&r.date<=iso(end));let sum=(k,c)=>rs.filter(r=>r.kind===k&&currency(r)===c).reduce((a,r)=>a+r.amount,0);$('report').textContent=`${iso(start)} to ${iso(end)} | `+['USD','ZiG'].map(c=>`${c}: Income ${money(sum('income',c),c)} | Expenses ${money(sum('expense',c),c)} | Net savings ${money(sum('saving',c)-sum('withdrawal',c),c)}`).join(' || ')}$('period').onchange=report;$('reportDate').onchange=report;
$('photo').onchange=()=>{let f=$('photo').files[0];if(!f){$('preview').classList.add('hidden');return}let url=URL.createObjectURL(f);$('preview').src=url;$('preview').classList.remove('hidden')};
function fileData(f){return new Promise((resolve,reject)=>{let r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsDataURL(f)})}
$('add').onclick=async()=>{try{let kind=$('kind').value,c=$('currency').value,amount=cents($('amount').value),save=cents($('saveAmount').value||0),description=$('description').value.trim(),date=$('date').value;if(!Number.isSafeInteger(amount)||amount<=0||!date)throw Error('Enter a valid amount and date');if(kind==='income'&&c==='USD'&&(!Number.isSafeInteger(save)||save<0||save>amount))throw Error('Savings must be between $0 and income amount');let goal=$('category').value;if(kind==='withdrawal'){let available=records.filter(r=>r.goal===goal&&currency(r)==='USD').reduce((a,r)=>a+(r.kind==='saving'?r.amount:r.kind==='withdrawal'?-r.amount:0),0);if(amount>available)throw Error('Withdrawal exceeds savings in this goal')}let image=$('photo').files[0]?await fileData($('photo').files[0]):null;if(image&&image.length>4000000)throw Error('Image too large. Choose a smaller image.');let label=kind==='income'?`Income ${money(amount,c)}; save ${c==='USD'?money(save):'not applicable (ZiG)'}?`:`${kind} ${money(amount,c)}?`;if(!confirm('Confirm transaction: '+label))return;let id=uid();records.push({id,kind,currency:c,amount,description,date,category:goal,goal:['saving','withdrawal'].includes(kind)?goal:null,image});if(kind==='income'&&c==='USD'&&save)records.push({id:uid(),kind:'saving',currency:'USD',amount:save,description:'Saved from income: '+description,date,category:$('saveGoal').value,goal:$('saveGoal').value,sourceId:id,image:null});await persist();$('amount').value='';$('description').value='';$('saveAmount').value='0';$('photo').value='';$('preview').classList.add('hidden');$('msg').textContent='Transaction saved on this device.';render()}catch(e){$('msg').textContent=e.message}};
$('addGoal').onclick=async()=>{let name=$('goalName').value.trim(),target=cents($('goalTarget').value);if(!name||!Number.isSafeInteger(target)||target<=0)return alert('Enter a goal name and positive target');goals.push({id:uid(),name,target});await persist();$('goalName').value='';$('goalTarget').value='';render()};
$('export').onclick=async()=>{try{let salt=crypto.getRandomValues(new Uint8Array(16)),k=await derive(sessionPassword,salt),blob=await seal({records,goals},k),payload={format:'ledger4-backup-v1',salt:b64(salt),...blob};let url=URL.createObjectURL(new Blob([JSON.stringify(payload)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='ledger4-backup-'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);$('backupMsg').textContent='Encrypted backup created. Keep the file and your password safe.'}catch(e){$('backupMsg').textContent=e.message}};
$('restore').onchange=async()=>{try{let f=$('restore').files[0];if(!f)return;let data=JSON.parse(await f.text());if(data.format!=='ledger4-backup-v1')throw Error('Invalid backup format');let password=prompt('Enter the password used when this backup was created');if(!password)return;let k=await derive(password,unb64(data.salt)),v=await unseal(data,k);if(!Array.isArray(v.records)||!Array.isArray(v.goals))throw Error('Invalid backup data');if(!confirm('Replace all current records with this backup?'))return;records=v.records;goals=v.goals;await persist();render();$('backupMsg').textContent='Backup restored.'}catch(e){$('backupMsg').textContent='Restore failed: '+e.message}};$('lock').onclick=lock;['pointerdown','keydown'].forEach(e=>document.addEventListener(e,()=>lastActivity=Date.now()));setInterval(()=>{if(key&&Date.now()-lastActivity>Number($('timeout').value)*60000)lock()},10000);setInterval(()=>{if(key&&!localStorage.getItem('ledger4-backup-reminder')||key&&Date.now()-Number(localStorage.getItem('ledger4-backup-reminder'))>7*86400000){$('backupMsg').textContent='Reminder: export an encrypted backup this week.';localStorage.setItem('ledger4-backup-reminder',Date.now())}},60000);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});choices();

// Optional browser-native, on-device text recognition. No network requests or guessed values.
$('recognise').onclick=async()=>{
 const status=$('ocrStatus'),f=$('photo').files[0];
 if(!f){status.textContent='Select a receipt or screenshot first.';return}
 if(typeof TextDetector==='undefined'){status.textContent='Offline text recognition is not supported by this browser. Enter details manually; the image can still be attached.';return}
 status.textContent='Reading photo locally…';
 try{const bitmap=await createImageBitmap(f);try{const result=await new TextDetector().detect(bitmap);const text=result.map(x=>x.rawValue||'').join('\n');$('ocrText').value=text;$('ocrReview').classList.toggle('hidden',!text);status.textContent=text?'Text found. Review it carefully before applying.':'No readable text found. Enter details manually.'}finally{bitmap.close()}}catch(e){status.textContent='Could not read this image offline. Enter details manually.'}
};
$('applyOcr').onclick=()=>{
 const t=$('ocrText').value,lines=t.split(/\n/).map(x=>x.trim()).filter(Boolean);
 const explicit=t.match(/(?:USD|US\$|ZiG|ZWG|ZIG|\$)\s*([0-9][0-9,]*(?:\.[0-9]{2})?)/i);
 if(explicit){const cur=/zig|zwg/i.test(explicit[0])?'ZiG':'USD';$('currency').value=cur;choices();$('amount').value=explicit[1].replace(/,/g,'')}
 const d=t.match(/\b(20\d{2})[-\/](0?[1-9]|1[0-2])[-\/](0?[1-9]|[12]\d|3[01])\b/);
 if(d)$('date').value=d[1]+'-'+d[2].padStart(2,'0')+'-'+d[3].padStart(2,'0');
 if(lines.length&&!$('description').value)$('description').value=lines[0].slice(0,120);
 $('ocrStatus').textContent='Proposed details filled where clearly labelled. Check all fields, especially the TOTAL, before saving.';
};
